# Generated by Django 5.0.6 on 2024-07-17 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Asset_movement_data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('permanent', 'Permanent'), ('temporary', 'Temporary')], max_length=200)),
                ('movement_date', models.DateTimeField(blank=True, null=True)),
                ('return_date', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Asset Movement',
            },
        ),
        migrations.CreateModel(
            name='AssetData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asset_name', models.CharField(max_length=200)),
                ('model', models.CharField(max_length=200)),
                ('serial_number', models.CharField(max_length=200, unique=True)),
                ('purchase_date', models.DateField()),
                ('warranty_info', models.CharField(max_length=200)),
                ('price', models.CharField(max_length=200)),
                ('custom_fields', models.JSONField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Asset Data',
                'ordering': ['asset_name'],
            },
        ),
        migrations.CreateModel(
            name='AssetImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images')),
            ],
        ),
        migrations.CreateModel(
            name='AssetType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Depreciation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField()),
                ('depreciation_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('salvage_value', models.DecimalField(decimal_places=2, max_digits=10)),
                ('useful_life', models.PositiveIntegerField()),
                ('depreciation_method', models.CharField(choices=[('straight_line', 'Straight Line'), ('declining_balance', 'Declining Balance'), ('sum_of_years_digits', 'Sum of the Years Digits')], max_length=50)),
            ],
        ),
    ]
