# Generated by Django 5.0.6 on 2024-07-17 09:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('asset_App', '0001_initial'),
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset_movement_data',
            name='from_branch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movements_from', to='authentication.branches'),
        ),
        migrations.AddField(
            model_name='asset_movement_data',
            name='to_branch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movements_to', to='authentication.branches'),
        ),
        migrations.AddField(
            model_name='assetdata',
            name='branch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.branches'),
        ),
        migrations.AddField(
            model_name='assetdata',
            name='office',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.headoffice'),
        ),
        migrations.AddField(
            model_name='asset_movement_data',
            name='asset',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='asset_App.assetdata'),
        ),
        migrations.AddField(
            model_name='assetimage',
            name='asset',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='asset_App.assetdata'),
        ),
        migrations.AddField(
            model_name='assetdata',
            name='asset_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assets', to='asset_App.assettype'),
        ),
        migrations.AddField(
            model_name='depreciation',
            name='asset',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='asset_App.assetdata'),
        ),
    ]
