# Generated by Django 5.0.6 on 2024-07-17 11:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset_App', '0002_initial'),
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='depreciation',
            name='branch',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='authentication.branches'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='depreciation',
            name='office',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='authentication.headoffice'),
            preserve_default=False,
        ),
    ]
