# Generated by Django 5.0.6 on 2024-07-19 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset_App', '0005_depreciation_custom_percentages_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='depreciation',
            old_name='depreciation_amount',
            new_name='purchase_value',
        ),
        migrations.RemoveField(
            model_name='depreciation',
            name='year',
        ),
        migrations.AlterField(
            model_name='depreciation',
            name='depreciation_method',
            field=models.CharField(choices=[('straight_line', 'Straight Line'), ('declining_balance', 'Declining Balance'), ('sum_of_years_digits', 'Sum of the Years Digits'), ('other', 'Other')], max_length=20),
        ),
        migrations.AlterField(
            model_name='depreciation',
            name='salvage_value',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
