# Generated by Django 5.0.6 on 2024-07-22 10:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset_App', '0006_rename_depreciation_amount_depreciation_purchase_value_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='depreciation',
            name='asset',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='depreciations', to='asset_App.assetdata'),
        ),
    ]
