# Generated by Django 5.0.6 on 2024-07-30 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset_App', '0008_remove_assetdata_custom_fields_alter_assetdata_model_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='depreciation',
            name='is_custom',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
