# Generated by Django 5.0.6 on 2024-10-14 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset_App', '0009_depreciation_is_custom'),
    ]

    operations = [
        migrations.AddField(
            model_name='assetdata',
            name='asset_code',
            field=models.CharField(default='', max_length=200, unique=True),
            preserve_default=False,
        ),
    ]
