# Generated by Django 5.0.6 on 2024-10-14 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset_App', '0010_assetdata_asset_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset_movement_data',
            name='quantity',
            field=models.PositiveIntegerField(default=1234),
            preserve_default=False,
        ),
    ]
