# Generated by Django 5.0.6 on 2024-10-14 11:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('asset_App', '0011_asset_movement_data_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='asset_movement_data',
            name='quantity',
        ),
    ]
