# Generated by Django 5.0.6 on 2024-10-14 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset_App', '0012_remove_asset_movement_data_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='assetdata',
            name='is_sold',
            field=models.BooleanField(default=False),
        ),
    ]
