# Generated by Django 5.0.6 on 2024-10-18 04:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset_App', '0014_alter_assettype_name'),
        ('authentication', '0010_alter_client_client_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='assettype',
            name='office',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='authentication.headoffice'),
        ),
    ]
