# Generated by Django 5.0.6 on 2024-10-18 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset_App', '0015_assettype_office'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assettype',
            name='name',
            field=models.CharField(max_length=200),
        ),
    ]
