# Generated by Django 5.0.6 on 2024-10-18 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset_App', '0016_alter_assettype_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='assetdata',
            name='is_auto_generated',
            field=models.BooleanField(default=False),
        ),
    ]
