# Generated by Django 5.0.6 on 2024-10-18 07:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset_App', '0017_assetdata_is_auto_generated'),
        ('authentication', '0011_departments'),
    ]

    operations = [
        migrations.AddField(
            model_name='assetdata',
            name='department',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='authentication.departments'),
            preserve_default=False,
        ),
    ]
