# Generated by Django 5.0.6 on 2024-10-18 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset_App', '0018_assetdata_department'),
    ]

    operations = [
        migrations.AddField(
            model_name='assetimage',
            name='biils_image',
            field=models.FileField(blank=True, null=True, upload_to='asset_bills'),
        ),
    ]
