# Generated by Django 5.0.6 on 2024-10-18 12:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset_App', '0019_assetimage_biils_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assetimage',
            name='biils_image',
        ),
        migrations.CreateModel(
            name='AssetBill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bill_file', models.FileField(blank=True, null=True, upload_to='asset_bills')),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bills', to='asset_App.assetdata')),
            ],
        ),
    ]
