# Generated by Django 5.0.6 on 2024-10-19 09:15

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset_App', '0020_remove_assetimage_biils_image_assetbill'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assetdata',
            name='price',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
    ]
