# Generated by Django 5.0.6 on 2024-10-19 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset_App', '0021_alter_assetdata_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assetdata',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
