# Generated by Django 5.0.6 on 2024-10-21 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset_App', '0022_alter_assetdata_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assettype',
            name='name',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
