# Generated by Django 5.0.6 on 2024-10-22 16:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('asset_App', '0023_alter_assettype_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='assetdata',
            options={'ordering': ['-purchase_date']},
        ),
    ]
