# Generated by Django 5.0.6 on 2024-10-25 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset_App', '0024_alter_assetdata_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assetdata',
            name='is_auto_generated',
        ),
        migrations.AddField(
            model_name='assetdata',
            name='custodian',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
