# Generated by Django 5.0.6 on 2024-10-25 10:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset_App', '0027_assetdata_verified'),
        ('authentication', '0015_remove_branches_user_remove_headoffice_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='assetdata',
            name='verified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_assets', to='authentication.headoffice'),
        ),
        migrations.AddField(
            model_name='assetdata',
            name='verified_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
