# Generated by Django 5.1.3 on 2024-11-21 11:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('asset_App', '0028_assetdata_verified_by_assetdata_verified_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assetdata',
            name='verified_by',
        ),
        migrations.RemoveField(
            model_name='assetdata',
            name='verified_date',
        ),
    ]
