# Generated by Django 5.1.2 on 2024-12-05 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset_App', '0030_alter_assetdata_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assetdata',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
