# Generated by Django 5.1.2 on 2024-12-05 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset_App', '0031_alter_assetdata_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assetdata',
            name='price',
            field=models.DecimalField(decimal_places=5, max_digits=10),
        ),
    ]
