# Generated by Django 5.1.2 on 2024-12-05 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset_App', '0032_alter_assetdata_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assetdata',
            name='price',
            field=models.DecimalField(decimal_places=5, max_digits=30),
        ),
        migrations.AlterField(
            model_name='depreciation',
            name='purchase_value',
            field=models.DecimalField(decimal_places=10, max_digits=30),
        ),
        migrations.AlterField(
            model_name='depreciation',
            name='salvage_value',
            field=models.DecimalField(blank=True, decimal_places=10, max_digits=30, null=True),
        ),
    ]
