# Generated by Django 5.0.6 on 2024-10-17 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_remove_client_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='branches',
            name='logo_image',
            field=models.ImageField(default='', upload_to='offiec_logo'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='headoffice',
            name='logo_image',
            field=models.ImageField(default='', upload_to='offiec_logo'),
            preserve_default=False,
        ),
    ]
