# Generated by Django 5.0.6 on 2024-10-17 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_branches_logo_image_headoffice_logo_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='logo_image',
            field=models.ImageField(default='', upload_to='offiec_logo'),
            preserve_default=False,
        ),
    ]
