# Generated by Django 5.0.6 on 2024-10-17 06:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0006_client_has_head_office'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='has_head_office',
        ),
    ]
