# Generated by Django 5.0.6 on 2024-10-17 08:07

import authentication.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0009_alter_customuser_is_admin_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='client_contact',
            field=models.CharField(help_text='Enter phone number with country code (e.g., +911234567890)', max_length=15, unique=True, validators=[authentication.models.validate_phone_number]),
        ),
    ]
