# Generated by Django 5.0.6 on 2024-10-22 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0011_departments'),
    ]

    operations = [
        migrations.AddField(
            model_name='departments',
            name='qr_code',
            field=models.ImageField(blank=True, null=True, upload_to='department_qr_codes/'),
        ),
    ]
