# Generated by Django 5.0.6 on 2024-10-23 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0013_chairman_commissionmembers'),
    ]

    operations = [
        migrations.AddField(
            model_name='commissionmembers',
            name='departments',
            field=models.ManyToManyField(to='authentication.departments'),
        ),
    ]
