# Generated by Django 5.0.6 on 2024-10-24 09:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0014_commissionmembers_departments'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='branches',
            name='user',
        ),
        migrations.RemoveField(
            model_name='headoffice',
            name='user',
        ),
    ]
