# Generated by Django 5.1.3 on 2024-11-21 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0015_remove_branches_user_remove_headoffice_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chairman',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='commissionmembers',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='departments',
            name='dpt_name',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
