# Generated by Django 5.1.3 on 2024-11-21 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0017_alter_departments_dpt_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='departments',
            name='dpt_name',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
